options:
  # 自动更新 (建议关闭)
  auto-update: false
  # 装备的更新周期
  armor-update-interval: 10
  # 是否在玩家第一次加入服务器时给予粘液科技指南
  give-guide-on-first-join: true
  # 是否在加载时输出 "载入中" 之类的信息
  print-out-loading: false
  # 是否在加载时输出 获取 Github 数据信息
  print-out-github-data-retrieving: false
  # 是否启用装备的特别效果 (例如萤石头盔的夜视)
  enable-armor-effects: true
  # 插件前缀
  prefix: '&a&lSlimefun &7>'
  # 自动保存周期
  auto-save-delay-in-minutes: 10
  # 是否在指南内显示原版合成表
  show-vanilla-recipes-in-guide: true
  # 是否允许创造模式自动全解
  allow-free-creative-research: true
  # 绿宝石附魔上限 [附属设置]
  emerald-enchantment-limit: 2
  # 解锁研究后自动燃放烟花
  research-unlock-fireworks: true
  # 解锁研究后让玩家自己燃放烟花
  research-give-fireworks: true
guide:
  # 是否将指南样式默认为 书与笔 GUI
  default-view-book: false
URID:
  info-delay: 3000
  # 自定义 Ticker 延迟
  custom-ticker-delay: 12
  # 是否启用 Tickers
  enable-tickers: true
items:
  # 是否启用护身符
  talismans: true
  # 是否启用小冰箱
  coolers: true
  # 是否启用背包
  backpacks: true
research-ranks:
# 研究段位
- Chicken
- Cow
- Spider
- Villager
- Beginner
- Clumsy Student
- Unskilled Student
- Incompetent Student
- Student
- Clumsy Apprentice
- Apprentice
- Skilled Apprentice
- Upcoming Mage
- Excellent Mage
- Young Magician
- Incompetent Magician
- Common Magician
- Magician
- Proficient Magician
- Skilled Magician
- Accustomed Magician
- Great Magician
- Clumsy Wizard
- Wizard
- Common Wizard
- Skilled Wizard
- Great Wizard
- Impressive Wizard
- Young Master
- Clumsy Master
- Upcoming Master
- Competent Master
- Master
- Skilled Master
- Excellent Master
- Great Master
- Proficient Master
- The chosen One
